id             = "extension-id"
name           = "extension name"
description    = "super cool awesome extension"
version        = "0.0.1"
authors        = ["Your name <your@email.com>"]
repository     = "https://github.com/not-a-cowfr/zed-extension-template"
schema_version = 1

# for snippets
snippets = "./snippets/<language>.json"
